jwt:
  token:
    secret-key: ${SECRET_KEY}

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  cloud:
    gateway:
      #<<< API Gateway / Routes
      routes:
        - id: Member
          uri: http://localhost:9091
          predicates:
            - Path=/api/member/**
        - id: location
          uri: http://localhost:9093
          predicates:
            - Path=/location/**,
        - id: review
          uri: http://localhost:9093
          predicates:
            - Path=/api/review/**
      #>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:9091"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 9090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=DEBUG:
